### ISSUE TITLE
colorbrewer_schemes.js

### ISSUE THREAD

**Issue by ericmelse** [wbuchanan/brewscheme#15]
Dear William,

I have tried to run brewdb, ref
but I get the following error prompt back from Stata (14.1 rev. 29-10-2015):

file http://www.colorbrewer2.org/colorbrewer_schemes.js not found
server says file permanently redirected to http://colorbrewer2.org/colorbrewer_schemes.js

Inspecting your brewdb.ado file, I do see the reference in line 59
so, it puzzles me what goes wrong here.

Best regards,
Eric

**Comment by wbuchanan** [comment]
This is an issue with a redirect occurring on the server side for colorbrewer.  I just checked things now and found that this part of the code in the master branch (it may be slightly ahead of the version on the SSC, but not by much).  brewdb.ado in the dev branch (and on the gh-pages branch where you can net install it from) both use an updated reference to the redirected page.  It isn't really something that I would be able to fix without doing a ton of lower-level work in C (which I don't know)/Java (which I know a bit of) to handle redirects.  Since it is already corrected in the dev branch, I'd recommend just using that version of things (and once enough of the functionality has been tested for something of a more stable release I'll push everything into the master branch in a big batch).  Thanks for bring this up though.  It caught me off guard when I was working on the newest version(s) of brewscheme/brewtheme that automatically generate the color blind transformed versions of the files.
