### ISSUE TITLE
variable newline not found

### ISSUE THREAD

**Issue by BjarteAAGNES** [wbuchanan/brewscheme#43]
**Removing brewscheme:** #41 

ado, find(brewscheme)
ado uninstall [96]
erase  H:\Stata\ado\plus/b\brewthemedata.do

**Installing brewscheme:**

net set ado PLUS
net inst brewscheme, from("https://wbuchanan.github.io/brewscheme/") replace
brewcolordb, rep

. brewscheme, scheme(set1) allst(set1) allc(8) allsat(80)
**variable newline not found**

part of trace:

```
begin brewtheme 
    begin brewtheme.themedata
       begin la  
           begin label
            ... 
            ...  
          - else {
          - _label `macval(0)'
          = _label var newline "Scheme File Lines to Insert Following This Line"
          variable newline not found
            }

           end label  
       end la  
    end brewtheme.themedata  
end brewtheme 
```

**Comment by wbuchanan** [comment]
@BjarteAAGNES check for a file named `brewthemedata.do` on the system.  There is a .do file that `brewtheme` calls to build out a dataset at runtime with all the default values (and includes an option to load those data after the program finished execution).  I'm not sure why that would fail, but there is a variable in that data set that is used to define the number of new line characters to insert following each line.  This was done to make it easier to use tools like `diff` to examine similarities/difference between the user generated scheme file and the `scheme-s2color.scheme` file.  On non-*nix based systems (but not necessarily limited to that platform) installing from the project page spins up the JVM so I couldn't do an exact replicate of what you did without restarting Stata after the install:

```
net inst brewscheme, from("https://wbuchanan.github.io/brewscheme/")

// [Restarted here]
. brewcolordb, rep over
(142 real changes made)

. brewdb, rep
The directory c:\ado\personal/b was successfully created.

. ls `"`c(sysdir_personal)'"'
  <dir>   3/28/16 11:43  .                 
  <dir>   3/28/16 11:43  ..                
  <dir>   3/28/16 11:43  b                 
  <dir>   3/28/16 11:43  brewcolors        
  <dir>   3/28/16 11:43  brewuser          
   0.5k  11/20/00 16:28  inputst.ado       
   0.0k  11/20/00 16:29  inputst.hlp       
   0.3k  11/24/00 17:34  outputst.ado      
   0.0k  11/20/00 16:30  outputst.hlp      
  16.0k   5/16/07 19:52  stado.exe         
   0.2k   2/26/16 17:08  stcmd.ado         
   3.1k  11/25/00 16:56  stcmd.hlp         
 764.0k   3/01/16 16:09  strutils.jar      
  <dir>   3/28/16 11:43  style             

. brewscheme, scheme(set1) allst(set1) allc(8) allsat(80)


For bugs/issues, please submit issues to: 
http://github.com/wbuchanan/brewscheme
For additional information about the program visit: 
http://wbuchanan.github.io/brewscheme
```

I also copied this output along the other thread since it seems like it might be a good idea to think about other ways to get the directory structure set up to accommodate single user and networked environments.

**Comment by wbuchanan** [comment]
This is corrected on the dev branch now.
